inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'support/linked_list.rb'
    - 'node.rb'
    - 'main.rb'

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

